fixed error due to race/circular dependancy between lib/{text,format}.py
circular/race dependancy between lib/text.py & lib/format.py causing an error when loading dynamics/bash_grammar.py which imports them in an order that causes this error

this erro started when i stowed away the modules i don't need into modules_i_dont_need/ in commit:
commit 5746b38f4f069551f69158fc2ff4609c43af97ed
Author: Aselinux <aselinux@gmail.com>
Date:   Tue Aug 14 10:36:11 2018 +0100

    Stowing away modules I don't use

Loading dynamic grammar modules:
Error loading _dynamic_manager from C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\_dynamic_manager.py
Traceback (most recent call last):
  File "C:\NatLink\NatLink\MacroSystem\core\natlinkmain.py", line 322, in loadFile
    imp.load_module(modName,fndFile,fndName,fndDesc)
  File "C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\_dynamic_manager.py", line 128, in <module>
    import_dynamic_modules()
  File "C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\_dynamic_manager.py", line 120, in import_dynamic_modules
    package_name)
  File "C:\Python27\Lib\pkgutil.py", line 246, in load_module
    mod = imp.load_module(fullname, self.file, self.filename, self.etc)
  File "C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\dynamics\bash_grammar.py", line 15, in <module>
    from lib.text import SCText
  File "C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\lib\text.py", line 10, in <module>
    import lib.format
  File "C:\Users\uc222343\Documents\GitHub\dragonfly-scripts\lib\format.py", line 13, in <module>
    from lib.text import specialCharacterTranslations, specialCharacterTranslationsRe
ImportError: cannot import name specialCharacterTranslations